ofd/urls.py
from django.contrib import admin
from django.urls import path
from ofd_app import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', auth_views.LoginView.as_view(template_name='ofd_app/index.html', redirect_authenticated_user=True), name="login"),
    path('login/', auth_views.LoginView.as_view(template_name='ofd_app/index.html', redirect_authenticated_user=True), name="login"),
    path('logout/', auth_views.LogoutView.as_view(next_page='/login/'), name="logout"),
    path('product/', views.product, name='product'),
    path('product/<int:id>/', views.product, name='product'),
    path('products/', views.products, name='products'),
    path('products/delete', views.product_delete, name='product_delete'),
    path('user/', views.user, name='user'),
    path('users/', views.users, name='users'),
    path('user/<int:id>/', views.user, name='user'),
    path('user/delete', views.user_delete, name='user_delete'),
    path('user_product/<int:id>/', views.user_product, name='user_product'),
    path('reg/', views.user_reg, name='user_reg'),
    path('orders/', views.orders, name='orders'),
    path('stat_org/', views.stat_org, name='stat_org'),
    path('orders/exportxlsx/<int:id>/', views.exportxlsx, name='exportxlsx'),
    path('orders/exporttxt/<int:id>/', views.exporttxt, name='exporttxt'),
    path('feedback/', views.feedback, name='feedback'),
    path('contacts/', views.contacts, name='contacts'),
    path('instruction/', views.instruction, name='instruction'),
    path('change_password/', auth_views.PasswordChangeView.as_view(template_name='ofd_app/change_password.html', success_url='/products'), name="change_password"),
    path('forgot_password/', auth_views.PasswordResetView.as_view(template_name='ofd_app/forgot_password.html', success_url='/products'), name="forgot_password"),
    path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='ofd_app/forgot_password.html', success_url='/login'), name="password_reset_confirm" ),
    path('get_order_invoice/', views.get_order_invoice, name='get_order_invoice'),
    path('order_change_pay_sign/', views.order_change_pay_sign, name='order_change_pay_sign'),
    path('change_order/', views.change_order, name='change_order'),
    path('get_upd/', views.get_upd, name='get_upd'),
    path('logs/', views.logs, name='logs'),
    path('get_log_file/', views.get_log_file, name='get_log_file'),
    path('add_codes/', views.add_codes, name='add_codes'),
]

ofd_app/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.db.models import FilteredRelation, Q, F
from ofd_app.utils import to_int
from datetime import timedelta, datetime


# Create your models here.
class Product(models.Model):
    product_id = models.AutoField(primary_key = True)
    product_name = models.CharField("Имя продукта", max_length = 100, unique=True)
    product_moddate = models.DateTimeField("Дата модификации продукта", auto_now = True)
    product_adddate = models.DateTimeField("Дата добавления продукта", auto_now_add = True)
    product_cost = models.IntegerField("Базовая стоимость продукта", )
    product_is_active = models.BooleanField("Продукт активен?", default=True)

class User(AbstractUser):
    email = models.EmailField("Email")
    city = models.CharField("Город проживания", max_length=100, null=True, blank=True)
    inn = models.CharField("ИНН", max_length = 12)
    org = models.CharField("Организация", max_length=100)
    is_legal = models.BooleanField("Юридичиское лицо?", default=False)
    parent = models.ForeignKey("self", models.SET_NULL, null=True, related_name='children')
    products = models.ManyToManyField(Product, through="ProductUserRel", verbose_name="Продукты доступные пользователю")
    phone_number = models.CharField("Номер телефона", max_length = 18)

    def save(self, *args, **kwargs):
        if self.id is not None and self.is_manager():
            need_update_childs = False
            db_object = User.objects.get(id=self.id)
            if db_object.inn != self.inn:
                need_update_childs = True
            if db_object.org != self.org:
                need_update_childs = True
            if db_object.is_active != self.is_active:
                need_update_childs = True
            if need_update_childs:
                childs = self.get_childs(False)
                for user in childs:
                    user.inn = self.inn
                    user.org = self.org
                    user.is_active = self.is_active
                    user.save()
        super().save(*args, **kwargs)

    def is_manager(self, user=None):
        user = self if user is None else user
        return user.groups.filter(name='Manager').exists()

    def is_user(self, user=None):
        user = self if user is None else user
        return user.groups.filter(name='User').exists()

    def is_admin(self, user=None):
        user = self if user is None else user
        return user.groups.filter(name='Admin').exists()

    def get_childs(self, as_dict=True):
        users = User.objects.filter(parent=self).filter(is_active=True).order_by('username')
        return users.values() if as_dict else users

    def get_role(self):
        if self.is_admin():
            return 'Admin'
        elif self.is_manager():
            return 'Manager'
        elif self.is_user():
            return 'User'
        elif self.is_superuser:
            return 'God'

    def get_products(self):
        if self.is_user():
            filtered_user = self.parent
        else:
            filtered_user = self
        products = Product.objects.annotate(by_user=FilteredRelation('productuserrel', condition = Q(productuserrel__user=filtered_user))).filter(Q(by_user__isnull = True) | Q(by_user__user=filtered_user)).filter(product_is_active=True).values_list('product_id', 'product_name', 'product_cost', 'by_user__cost', named=True).order_by('product_name')
        return products

    def get_product(self, product_id):
        if self.is_user():
            filtered_user = self.parent
        else:
            filtered_user = self
        products = Product.objects.annotate(by_user=FilteredRelation('productuserrel', condition = Q(productuserrel__user=filtered_user))).filter(Q(by_user__isnull = True) | Q(by_user__user=filtered_user)).filter(product_is_active=True).filter(product_id=product_id).values_list('product_id', 'product_name', 'product_cost', 'by_user__cost', named=True).order_by('product_name')
        return products[0] if len(products) > 0 else None

    @staticmethod
    def get_organizations():
        orgs = User.objects.exclude(org__isnull=True).exclude(org='').exclude(is_active=False).values('org').distinct().order_by('org')
        return list(map(lambda x: { 'id': x['org'], 'value': x['org']}, orgs))

    def has_access_to_user(self, user):
        ##own profile
        if user.id == self.id:
            return True
        elif self.is_superuser:
            return True
        elif self.is_admin() and (not user.is_superuser):
            return True
        elif user.parent is not None and self.id == user.parent.id:
            return True
        return False

class ProductUserRel(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Пользователь")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="Продукт")
    cost = models.IntegerField("Стоимость продукта",)
    moddate = models.DateTimeField("Дата модификации связи", auto_now=True)
    adddate = models.DateTimeField("Дата добавления связи", auto_now_add=True)
    user_mod = models.IntegerField("Пользователь, который последний раз модифицировал запись",)
    class Meta:
        unique_together = ('user', 'product')
    
    @staticmethod
    def save_product_user_rel(post_costs, user, user_mod_id):
        products = Product.objects.all()
        for product in products:
            cost = to_int(post_costs.get('product_' + str(product.product_id), 0), 0)
            if cost > 0:
                try:
                    relation = ProductUserRel.objects.get(user=user, product=product)
                    relation.cost = cost
                    relation.user_mod = user_mod_id
                except ProductUserRel.DoesNotExist:
                    relation = ProductUserRel(user=user, product=product, cost=cost, user_mod=user_mod_id)
                relation.save()

class OrderStatus(models.Model):
    code = models.CharField("Код статуса", max_length = 1, primary_key = True)
    name = models.CharField("Название статуса", max_length = 10, null=True)

    def is_in_progress(self):
        return self.code == 'I'

    def is_approved(self):
        return self.code == 'A'

    def is_rejected(self):
        return self.code == 'R'

    @staticmethod
    def get_all_statuses():
        statuses = OrderStatus.objects.all().values('code', 'name').order_by('code')
        return list(map(lambda x: { 'id': x['code'], 'value': x['name']}, statuses))

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, verbose_name="Пользователь сделавший заказ")
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name="Заказанный продукт")
    status = models.ForeignKey(OrderStatus, on_delete=models.PROTECT, default='I', verbose_name="Статус")
    adddate = models.DateTimeField("Дата добавления заказа", auto_now_add=True)
    comment = models.TextField("Комментарий к заказу", null=True)
    codes = models.TextField("Коды активации", null=True)
    admin_comment = models.TextField("Ответ от администратора", null=True)
    amount = models.IntegerField("Количество")
    cost = models.IntegerField("Итоговая стоимость для одного продукта")
    is_paid = models.BooleanField("Статус оплаты заказа")
    date_of_payment = models.DateField("Дата оплаты заказа", null=True)

    def assign_status(self, status, comment, codes):
        try:
            new_status = OrderStatus.objects.get(code=status)
        except OrderStatus.DoesNotExist:
            return False

        if self.status.is_in_progress() and not new_status.is_in_progress():
            self.status = new_status
            if comment:
                self.admin_comment = comment
            if codes:
                self.codes = codes
            if self.status.is_approved():
                self.date_of_payment = datetime.today()
            self.save(update_fields=['status', 'admin_comment', 'codes', 'date_of_payment'])
            return True
        return False

    @staticmethod
    def get_orders(user, date_from=None, date_to=None, status_code=None, org=None, user_id=None, paid=None):
      if user.is_admin() or user.is_superuser:
          orders = Order.objects.all().annotate(user_role=F('user__groups__name')).filter(adddate__gte=date_from).filter(adddate__lt = date_to + timedelta(1))
          if org is not None and org != '*':
              orders = orders.filter(user__org=org)
          if paid is not None and paid != '*':
              orders = orders.filter(is_paid=bool(to_int(paid)))
      elif user.is_manager():
          orders = Order.objects.all().annotate(user_role=F('user__groups__name')).filter(Q(user__parent=user) | Q(user=user)).filter(adddate__gte=date_from).filter(adddate__lt = date_to + timedelta(1))
          if user_id is not None and user_id != '*':
            if int(user_id) > 0:
                orders = orders.filter(user__id=int(user_id))
      else:
          orders = Order.objects.all().annotate(user_role=F('user__groups__name')).filter(user=user).filter(adddate__gte=date_from).filter(adddate__lt = date_to + timedelta(1))
      if status_code is not None and status_code != '*':
          orders = orders.filter(status=status_code)
      return orders.order_by('-adddate')

    @staticmethod
    def get_order_codes(user, order_id):
        try:
            order = Order.objects.get(id=order_id)
            if user.is_user() and order.user.id == user.id:
                return order.codes
            if user.is_manager() and (order.user.id == user.id or order.user.parent.id == user.id):
                return order.codes
            if user.is_admin() or user.is_superuser:
                return order.codes

ofd_app/forms.py
from django import forms
from .models import Product
from .models import User
#from .models import Profile
from django.contrib.auth.forms import UserCreationForm
from ofd_app import views
from django.utils.translation import gettext_lazy as _

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('product_name', 'product_cost')

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'inn', 'phone_number', 'org', 'city')
        labels = {'username': _('Логин'), 'city': _('Город')}

    def __init__(self, *args, **kwargs):
        self.requested_user = kwargs.pop('requested_user', None)
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['readonly'] = True
        if self.can_change_inn_org():
            self.fields['inn'].widget.attrs['readonly'] = True
            self.fields['org'].widget.attrs['readonly'] = True
    def clean_inn(self):
        if self.can_change_inn_org():
            return self.instance.inn
        return self.cleaned_data['inn']
    def clean_org(self):
        if self.can_change_inn_org():
            return self.instance.org
        return self.cleaned_data['org']
    def clean_username(self):
        return self.instance.username
    def can_change_inn_org(self):
        return self.requested_user is not None and not (self.requested_user.is_superuser or self.requested_user.is_admin()) or self.instance.is_user()

class UserCreationFormCustom(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'inn', 'phone_number', 'org', 'city')
        labels = {'username': _('Логин'), 'city': _('Город')}

    def __init__(self, *args, **kwargs):
        self.requested_user = kwargs.pop('requested_user', None)
        super().__init__(*args, **kwargs)
        if self.requested_user is not None and self.requested_user.is_manager():
            self.fields.pop('inn')
            self.fields.pop('org')
        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

ofd_app/templates/ofd_app/css_version.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static "stylesheet_v5.css" %}">

ofd_app/templates/ofd_app/filter.html
<script type="text/javascript">
jQuery(function($){
	$.datepicker.regional['ru'] = {
		closeText: 'Закрыть',
		prevText: '&#x3c;Пред',
		nextText: 'След&#x3e;',
		currentText: 'Сегодня',
		monthNames: ['Январь','Февраль','Март','Апрель','Май','Июнь',
		'Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'],
		monthNamesShort: ['Янв','Фев','Мар','Апр','Май','Июн',
		'Июл','Авг','Сен','Окт','Ноя','Дек'],
		dayNames: ['воскресенье','понедельник','вторник','среда','четверг','пятница','суббота'],
		dayNamesShort: ['вск','пнд','втр','срд','чтв','птн','сбт'],
		dayNamesMin: ['Вс','Пн','Вт','Ср','Чт','Пт','Сб'],
		weekHeader: 'Нед',
		dateFormat: 'yy-mm-dd',
		firstDay: 1,
		isRTL: false,
		showMonthAfterYear: false,
		yearSuffix: ''};
	$.datepicker.setDefaults($.datepicker.regional['ru']);
});
</script> 

<script type="text/javascript">
    $(function() {
        $('#datep').datepicker();
    });
</script>
<script type="text/javascript">
    $(function() {
        $('#datep2').datepicker();
    });
</script>
<div class="container container_min_width">
	<form action="/orders/" method="POST" name="date_filter">
		{% csrf_token %}
		<label for="datep">От:&nbsp</label><input id="datep" name="date_from" autocomplete="off" value="{{ request.session.order_filters.date_from }}" class="DatepickerBox__DateFrom">
		<label for="datep">До:&nbsp</label><input id="datep2" name="date_to" autocomplete="off" value="{{ request.session.order_filters.date_to }}" class="DatepickerBox__DateTo">
		{% if perms.ofd_app.change_product %}
		<label for="org_filter">Организация:</label>
		<select class="DatepickerBox__Filter" id="org_filter" name="org_filter">
		  {% if request.session.order_filters.org == "*" %}	
		  <option selected value="*">Все</option>
		  {% else %}
		  <option value="*">Все</option>
		  {% endif %}
		  {% for org in filters.org %}
		  {% if request.session.order_filters.org == org.id %}
		  <option selected value="{{ org.id }}">{{ org.value }}</option>
		  {% else %}
		  <option value="{{ org.id }}">{{ org.value }}</option>
		  {% endif %}
		  {% endfor %}	
		</select>
		{% endif %}
		<label for="status_filter">Статус:</label>
		<select class="DatepickerBox__Filter" id="status_filter" name="status_filter">
			{% if request.session.order_filters.status == "*" %}
			<option selected value="*">Все</option>
			{% else %}
			<option value="*">Все</option>
			{% endif %}
			{% for status in filters.status %}
			{% if request.session.order_filters.status == status.id %}
			<option selected value="{{ status.id }}">{{ status.value }}</option>
			{% else %}
			<option value="{{ status.id }}">{{ status.value }}</option>
			{% endif %}
			{% endfor %}
		</select>
		{% if user_role == 'Admin' or request.user.is_superuser%}
		<label for="paid_filter">Оплата:</label>
		<select class="DatepickerBox__Filter" id="paid_filter" name="paid_filter">
			{% if request.session.order_filters.paid == "*" %}
			<option selected value="*">Все</option>
			{% else %}
			<option value="*">Все</option>
			{% endif %}
			{% if request.session.order_filters.paid == "1" %}
			<option selected value="1">Оплачен</option>
			{% else %}
			<option value="1">Оплачен</option>
			{% endif %}
			{% if request.session.order_filters.paid == "0" %}
			<option selected value="0">Не оплачен</option>
			{% else %}
			<option value="0">Не оплачен</option>
			{% endif %}
		</select>
		{% endif %}
		{% if user_role == 'Manager'%}
		<label for="status_filter">Сотрудник:</label>
		<select class="DatepickerBox__Filter" id="user_filter" name="user_filter">
			{% if request.session.order_filters.user == "*" %}
			<option selected value="*">Все</option>
			{% else %}
			<option value="*">Все</option>
			{% endif %}
			{% for user in filters.users %}
			{% if request.session.order_filters.user == user.id %}
			<option selected value="{{ user.id }}">{{ user.first_name }}&nbsp{{ user.last_name }}</option>
			{% else %}
			<option value="{{ user.id }}">{{ user.first_name }}&nbsp{{ user.last_name }}</option>
			{% endif %}
			{% endfor %}
			</select>
		{% endif %}
		<button type="submit" class="btn DatepickerBox__FilterBtn" name="date_filter_button" value="add_filter">Применить</button>
	</form>
</div>

ofd_app/templates/ofd_app/forgot_password.html
<!doctype html>
<html lang="ru">
<head>

    {% load static %}

    {% load crispy_forms_tags %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=930, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static "bootstrap.css" %}">
    {% include "ofd_app/css_version.html" %}
    <link rel="icon" type="image/x-icon" href="{% static "favicon.ico" %}">
    <title>Восстановление пароля</title>
</head>
<body class="text-center">
    <div class="d-flex justify-content-center flex-grow-1 align-items-center">
        <div class="forgot_password">
            <form class="form-signin" id="input_form" method="post" action="">
                <h6>Восстановление пароля</h6>

                {% csrf_token %}

                {{ form|crispy }}

                <button class="btn btn_registration_form" type="submit" id="button_registration">Отправить</button>
            </form>
        </div>
    </div>
</body>
</html>

ofd_app/templates/ofd_app/instruction.html
<!doctype html>
<html lang="ru">
<head>

    {% load static %}

    {% load crispy_forms_tags %}

    <meta name="yandex-verification" content="df7d219eb0aed573">
    <meta charset="utf-8">
    <meta name="viewport" content="width=930, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static "bootstrap.css" %}">
    {% include "ofd_app/css_version.html" %}
    <link rel="icon" type="image/x-icon" href="{% static "favicon.ico" %}">
    <title>Инструкция</title>
</head>
<body class="text-center">

    {% include "ofd_app/menu.html" %}

    <div class="content flex-grow-1">
        <iframe width="930" height="524" src="https://www.youtube.com/embed/J_reoLfi7Tc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>

    {% include "ofd_app/footer.html" %}

</body>
</html>

ofd_app/templates/ofd_app/menu.html
<!-- Навигационная панель сверху страницы -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="//ajax.aspnetcdn.com/ajax/jquery.ui/1.10.3/jquery-ui.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<div class="nav_div">
    <div class="top_menu_link_div">
      <a href="/products/">
        <img src="/static/logo.png" alt="Логотип mir-ofd.ru">
      </a>
    </div>

    {% if path == "products" %}

    <div class="top_menu_link_active">
    	<a href="/products/" class="nav_link"><strong>Продукция</strong></a>
    </div>

    {% else %}

    <div class="top_menu_link_div">
    	<a href="/products/" class="nav_link"><strong>Продукция</strong></a>
    </div>

    {% endif %}

    {% if perms.ofd_app.change_product %}

    {% if perms.ofd_app.view_user %}

    {% if path == "users" %}

    <div class="top_menu_link_active">
    	<a href="/users/" class="nav_link"><strong>Пользователи</strong></a>
    </div>

    {% else %}

    <div class="top_menu_link_div">
    	<a href="/users/" class="nav_link"><strong>Пользователи</strong></a>
    </div>

    {% endif %}

    {% endif %}

    {% else %}

    {% if perms.ofd_app.view_user %}

    {% if path == "users" %}

    <div class="top_menu_link_active">
    	<a href="/users/" class="nav_link"><strong>Сотрудники</strong></a>
    </div>

    {% else %}

    <div class="top_menu_link_div">
    	<a href="/users/" class="nav_link"><strong>Сотрудники</strong></a>
    </div>

    {% endif %}

    {% endif %}

    {% endif %}

    {% if path == "my_card" %}

    <div class="top_menu_link_active">
    	<a href="/user/{{request.user.id}}" class="nav_link"><strong>Моя карточка</strong></a>
    </div>

    {% else %}

    <div class="top_menu_link_div">
    	<a href="/user/{{request.user.id}}" class="nav_link"><strong>Моя карточка</strong></a>
    </div>

    {% endif %}

    {% if path == "orders" %}

    <div class="top_menu_link_active">

        {% if perms.ofd_app.view_user %}

        <a href="/orders" class="nav_link"><strong>Заказы</strong></a>

        {% else %}

        <a href="/orders" class="nav_link"><strong>Мои заказы</strong></a>

        {% endif %}

    </div>

    {% else %}

    <div class="top_menu_link_div">

      {% if perms.ofd_app.view_user %}

      <a href="/orders" class="nav_link"><strong>Заказы</strong></a>

      {% else %}

      <a href="/orders" class="nav_link"><strong>Мои заказы</strong></a>

      {% endif %}

  </div>

    {% endif %}

    {% if user_role == "Admin" or user_role == "God" %}

    {% if path == "stat" %}

    <div class="top_menu_link_active">
      <a href="/stat_org" class="nav_link"><strong>Статистика</strong></a>
    </div>

    {% else %}

    <div class="top_menu_link_div">
      <a href="/stat_org" class="nav_link"><strong>Статистика</strong></a>
    </div>

    {% endif %}

    {% endif %}

    <div class="w-100"></div>

    {% if path == "instruction" %}

     <div class="top_menu_link_active">
      <a href="/instruction" class="nav_link"><strong>Инструкция</strong></a>
    </div>

    {% else %}

     <div class="top_menu_link_div">
      <a href="/instruction" class="nav_link"><strong>Инструкция</strong></a>
    </div>

    {% endif %}

    {% if path == "feedback" %}

     <div class="top_menu_link_active mr-2">
      <a href="/feedback" class="nav_link"><strong>Контакты</strong></a>
    </div>

    {% else %}

     <div class="top_menu_link_div mr-2">
      <a href="/feedback" class="nav_link"><strong>Контакты</strong></a>
    </div>

    {% endif %}

    <div class="btn-group dropleft top_select_box">
        <button type="button" class="btn dropdown-toggle top_select_box_button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-cog fontawesome_gear"></i>
        </button>
        <div class="dropdown-menu">

          {% if user_role == "God" %}

          <a class="dropdown-item" href="/user/">Добавить администратора</a>

          {% elif user_role == "Admin" %}

          <a class="dropdown-item" href="/user/">Добавить менеджера</a>

          {% elif user_role == "Manager" %}

          <a class="dropdown-item" href="/user/">Добавить сотрудника</a>

          {% endif %}

          {% if perms.ofd_app.change_product %}

          <a class="dropdown-item" href="/product/">Добавить продукт</a>

          {% endif %}

          {% if user_role == "God" or user_role == "Admin" or user_role == "Manager" %}

          {% if can_delete %}

          <button type="submit" class="btn dropdown-item" form="top_form">Удалить отмеченное</button>

          {% else %}

          <button type="submit" class="btn dropdown-item disabled" form="top_form">Удалить отмеченное</button>

          {% endif %}

          {% endif %}

          {% if user_role == "God" or user_role == "Admin" %}

          {% if path == "orders" %}

          <button type="submit" class="btn dropdown-item" form="is_paid_form">Изменить статус оплаты</button>

          {% else %}

          <button type="submit" class="btn dropdown-item disabled" form="is_paid_form">Изменить статус оплаты</button>

          {% endif %}

          {% endif %}

          <a class="dropdown-item" href="/change_password">Сменить пароль</a>
        </div>
      </div>
    <div class="top_menu_link_div_exit">
    	<a href="/logout" class="nav_link"><strong>Выход</strong></a>
    </div>
</div>
<script>
$(function () {
    $('[data-toggle="popover"]').popover()
})
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>

ofd_app/templates/ofd_app/order.html
<!doctype html>
<html lang="ru">
<head>
	{% load static %}
	{% load crispy_forms_tags %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=930, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static "bootstrap.css" %}">
    {% include "ofd_app/css_version.html" %}
    <link rel="icon" type="image/x-icon" href="{% static "favicon.ico" %}">
    <title>Информация о заказе</title>
</head>
<body class="text-center">
		{% include "ofd_app/menu.html" %}
    <div class="container">
		<table class="table table-striped table-sm">
			<thead>
				<tr>
					<th scope="col">Наименование продукта</th>
					<th scope="col">Стоимость</th>
					<th scope="col">Количество</th>
					<th scope="col">Сумма</th>
				</tr>
			</thead>
			<tbody>
				{% for product in order %}
				<tr>
					<td>{{ product.product_name }}</td>
					<td>{{ product.cost }}</td>
					<td>{{ product.amount }}</td>
					<td>{{ product.full_cost }}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		<h4>Итог: {{total}}</h4>
		</div>
		{% include "ofd_app/footer.html" %}
</body>
</html>

ofd_app/templates/ofd_app/user_reg.html
<!doctype html>
<html lang="ru">
<head>
    {% load static %}
    {% load crispy_forms_tags %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=930, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static "bootstrap.css" %}">
    {% include "ofd_app/css_version.html" %}
    <link rel="icon" type="image/x-icon" href="{% static "favicon.ico" %}">
    <title>Регистрация</title>
</head>
<body class="text-center">
    <div class="d-flex justify-content-center">
        <div class="registration_form_start">
            <form class="form-signin" id="input_form" method="post" action="">
                {% csrf_token %}
                <h5>Регистрация</h5>
                {% csrf_token %}
                {{ reg_form|crispy }}
                {{ profile_form|crispy }}
                <button class="btn btn_registration_form" type="submit" id="button_registration">Зарегистрироваться</button>
            </form>
        </div>
    </div>
</body>
</html>